language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install -y libqt4-dev libinsighttoolkit3-dev libtclap-dev libvtk5-dev libvtk5-qt4-dev libgdcm2-dev libfftw3-dev

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/../install

script:
  - make
  - make install
