version: 0.4.9.{build}

init:
  - cmd: git config --global core.autocrlf true
  - cmd: dir C:\projects
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\nifti2dicom

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

branches:
  except:
    - travis

before_build:
  - cmd: md C:\projects\ycm\build
  - cmd: cd C:\projects\ycm\build
  - cmd: if "%platform%"=="Win32" cmake -G"Visual Studio 12" -DCMAKE_INSTALL_PREFIX:PATH=C:\projects\nifti2dicom\install
  - cmd: if "%platform%"=="x64" cmake -G"Visual Studio 12 Win64" -DCMAKE_INSTALL_PREFIX:PATH=C:\projects\nifti2dicom\install

build:
  project: C:\projects\ycm\build\Nifti2Dicom.sln

after_build:
  - cmd: cmake --build C:\projects\ycm\build --target INSTALL
  - cmd: cmake --build C:\projects\ycm\build --target PACKAGE

test_script:
  - cmd: ctest -VV

artifacts:
  - path: 'build\*.msi'
  - path: 'build\*.zip'
